build:
  image: fracting/msys32:w1.9.5-m2.5.0-4
  pull: true
  shell: $$platform
  commands:
    - cd src
    - make wm_names.t
    - make vk_names.t
    - cd ..
    - make
    - bin/mintty.exe --help
    - bin/mintty.exe --version
      #    - mintty.exe --log mintty.log --exec echo hello mintty
    - ls -al
    - pwd
    - cat mintty.log
    - grep hello mintty.log

matrix:
  platform:
#    - cygwin32
    - msys32
